// Single source for the module manifest and its runtime DSP contract.
import fs from 'node:fs';
// Ten controls: six geometric, four for the amplitude envelope. A per-note
// modulation envelope with a routable destination lived here and was removed --
// the two controls worth modulating, Pinch and Spikes, carry their character in
// the operator ratio, and moving that under a held note is heard as a
// glissando rather than as timbre. See the removal commit.
const keys=['morph','bulge','pinch','spikes','tilt','wobble','attack','decay','sustain','release'];
const names=['Morph','Bulge','Pinch','Spikes','Tilt','Wobble','Attack','Decay','Sustain','Release'];
const short=['Mrph','Blge','Pnch','Spke','Tilt','Wobl','Atk','Dec','Sus','Rel'];
const defaults=[0,0,0,0,.5,0,.05,.25,1,.25];
const min=keys.map(()=>0),max=keys.map(()=>1);
const envelopeViz={attack:'attack',decay:'decay',sustain:'sustain',release:'release'};
const params=keys.map((key,i)=>({key,name:names[i],short_name:short[i],type:'float',min:min[i],max:max[i],step:.01,default:defaults[i],...(envelopeViz[key]?{viz:{group:'amp',role:envelopeViz[key]}}:{})}));
params.push({key:'preset',name:'Preset',type:'int',min:0,max:5,step:1,default:0},
 {key:'visual',name:'Activity',type:'string',access:'read'},
 // preset_browser merges this page INTO the level's preset browser instead of
 // adding a second one, and preset browsers are emitted before a level's grids
 // -- which is how the instrument lands on its own picture rather than on a
 // page of knobs. monksynth's face page does the same.
 {key:'shape',name:'Shape',short_name:'Shpe',type:'canvas',canvas_script:'canvas.js',as_page:true,preset_browser:true,extra_keys:['visual'],show_value:false});
const hierarchy={pad_layout:'chromatic',levels:{
 root:{label:'Bouba-Kiki',knobs:['morph','bulge','pinch','spikes','tilt','wobble','attack','release'],
  list_param:'preset',count_param:'preset_count',name_param:'preset_name',
  params:[{key:'shape'},...['morph','bulge','pinch','spikes','tilt','wobble','attack','release'].map(key=>({key})),
   {level:'envelope',label:'Envelope'}]},
 envelope:{label:'Envelope',knobs:['attack','decay','sustain','release'],params:['attack','decay','sustain','release'].map(key=>({key}))}
}};
const presets=[
 ['Pure Bouba',{}],
 ['Kiki Knock',{morph:.8,spikes:.45,attack:0,decay:.2,sustain:.3,release:.15}],
 ['Slow Prickle',{spikes:.7,pinch:.2,attack:.5,decay:.5,sustain:.8,release:.5}],
 ['Rubber Mouth',{bulge:.55,pinch:.45,attack:.08,decay:.35,sustain:.5,release:.3}],
 ['Glass Creature',{morph:.85,spikes:.25,pinch:.6,attack:.025,decay:.45,sustain:.25,release:.8}],
 ['Held Breath',{bulge:.08,morph:.3,wobble:.35,attack:.3,decay:.5,sustain:.9,release:.6}]
];
const values=presets.map(([,p])=>keys.map((k,i)=>p[k]??defaults[i]));
const module=JSON.parse(fs.readFileSync('src/module.json','utf8'));
// The version lives in src/module.json; releases bump it there, not here.
module.description='Contour synth — a shape drives FM operators';
module.capabilities.chain_params=params;module.ui_hierarchy=hierarchy;
fs.writeFileSync('src/module.json',JSON.stringify(module,null,2)+'\n');
const strings=a=>'{'+a.map(x=>JSON.stringify(x)).join(',')+'}';
const floats=a=>'{'+a.map(x=>Number(x).toFixed(6)+'f').join(',')+'}';
fs.writeFileSync('src/dsp/contract.h',`/* Generated by tools/compile_contract.mjs. */
#ifndef BK_CONTRACT_H
#define BK_CONTRACT_H
#define BK_PARAM_COUNT 10
#define BK_PRESET_COUNT 6
static const char *const KEYS[10]=${strings(keys)};
static const float DEFAULTS[10]=${floats(defaults)};
static const float MINIMUM[10]=${floats(min)},MAXIMUM[10]=${floats(max)};
static const char *const PRESET_NAMES[6]=${strings(presets.map(p=>p[0]))};
static const float PRESET_VALUES[6][10]={${values.map(floats).join(',\n')}};
static const char CHAIN_PARAMS[]=${JSON.stringify(JSON.stringify(params))};
static const char UI_HIERARCHY[]=${JSON.stringify(JSON.stringify(hierarchy))};
#endif
`);
console.log('Compiled 10 controls, one envelope page and six presets');
